# Generated by Django 3.2.3 on 2021-05-21 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0001_initial'),
        ('carts', '0002_auto_20210520_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_control.studentprofilemodel'),
        ),
        migrations.AlterField(
            model_name='orderpaymentmodel',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.ordermodel'),
        ),
    ]
