# Generated by Django 3.2.3 on 2021-05-18 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_control.universitymodel')),
            ],
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_control.departmentmodel')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_control.universitymodel')),
            ],
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('edition', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_control.coursemodel')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_control.departmentmodel')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_control.publisherprofilemodel')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_control.universitymodel')),
            ],
        ),
    ]
